- .asf.yaml
- .github/workflows/backend.yml
- DISCLAIMER
- LICENSE
- NOTICE
- pom.xml
- seatunnel-server/pom.xml
- seatunnel-web-dist/pom.xml
- seatunnel-web-dist/release-docs/binary/LICENSE
- seatunnel-web-dist/release-docs/binary/NOTICE
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-Jetty-9.x.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-aspectj.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-jakarta.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-javax-annotation.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-jsoup.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-logback.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-mapstruct.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-slf4j.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-spring-plugin.txt
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-swagger-core.txt
- seatunnel-web-dist/src/main/assembly/assembly-src.xml
- tools/dependencies/checkLicense.sh
- tools/dependencies/known-dependencies.txt
Add source package
Add github setting
> Add License and Notice files

- seatunnel-server/seatunnel-app/src/main/resources/script/init_sql.sh
- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_env.sh
- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_mysql.sql
https://github.com/apache/incubator-seatunnel/issues/2977
> [seatunnel-2977][seatunnel-server] add auth for server

- seatunnel-server/seatunnel-app/src/main/resources/script/init_sql.sh
- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_env.sh
- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_mysql.sql
> [Script]add init sql

- seatunnel-ui/src/locales/en_US/jobs.ts
- seatunnel-ui/src/service/task/index.ts
- seatunnel-ui/src/service/task/types.ts
- seatunnel-ui/src/views/jobs/list/index.tsx
- seatunnel-ui/src/views/jobs/list/use-table.ts
- seatunnel-ui/src/views/user-manage/list/use-table.ts
> [Feat][UI] Complete job management.

- pom.xml
- seatunnel-server/seatunnel-app/pom.xml
- seatunnel-server/seatunnel-app/src/main/resources/application.yml
- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_h2.sql
- seatunnel-web-dist/release-docs/binary/LICENSE
- seatunnel-web-dist/release-docs/binary/licenses/LICENSE-h2.txt
- tools/dependencies/known-dependencies.txt
> [Feature][Dao] Added h2 memory database.

- seatunnel-server/pom.xml
- seatunnel-server/seatunnel-app/pom.xml
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/aspect/LoginAspect.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/common/ObjectTypeEnum.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/ScriptController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/TaskController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/UserController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IScriptJobApplyDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/ScriptJobApplyDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/entity/JobDefine.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/mapper/ScriptJobApplyMapper.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/request/task/ExecuteReq.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/request/task/RecycleScriptReq.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/request/user/BaseUserReq.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/PageInfo.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/task/InstanceSimpleInfoRes.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/task/JobSimpleInfoRes.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/GlobalExceptionHandler.java
- seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/ScriptJobApplyMapper.xml
- seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/UserMapper.xml
- seatunnel-server/seatunnel-scheduler/seatunnel-scheduler-dolphinscheduler/src/main/java/org/apache/seatunnel/scheduler/dolphinscheduler/dto/ProcessDefinitionDto.java
- seatunnel-server/seatunnel-scheduler/seatunnel-scheduler-dolphinscheduler/src/main/java/org/apache/seatunnel/scheduler/dolphinscheduler/enums/ReleaseStateEnum.java
- seatunnel-server/seatunnel-scheduler/seatunnel-scheduler-dolphinscheduler/src/main/java/org/apache/seatunnel/scheduler/dolphinscheduler/enums/RunFrequencyEnum.java
- seatunnel-server/seatunnel-scheduler/seatunnel-scheduler-dolphinscheduler/src/main/java/org/apache/seatunnel/scheduler/dolphinscheduler/impl/DolphinschedulerServiceImpl.java
- seatunnel-server/seatunnel-scheduler/seatunnel-scheduler-dolphinscheduler/src/main/java/org/apache/seatunnel/scheduler/dolphinscheduler/impl/InstanceServiceImpl.java
- seatunnel-server/seatunnel-scheduler/seatunnel-scheduler-dolphinscheduler/src/main/java/org/apache/seatunnel/scheduler/dolphinscheduler/impl/JobServiceImpl.java
- seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
- seatunnel-server/seatunnel-spi/src/main/java/org/apache/seatunnel/spi/scheduler/dto/InstanceDto.java
- seatunnel-server/seatunnel-spi/src/main/java/org/apache/seatunnel/spi/scheduler/dto/JobSimpleInfoDto.java
Update api style follow front-end & product-design
> [Improve][seatunnel-server] Update api style follow front-end & product-design

- seatunnel-ui/src/components/modal/index.tsx
- seatunnel-ui/src/layouts/dashboard/index.tsx
- seatunnel-ui/src/themes/modules/light.ts
> [Feat][UI] Complete style writing.

- seatunnel-ui/src/layouts/dashboard/header/logo/index.tsx
- seatunnel-ui/src/layouts/dashboard/header/menu/index.tsx
- seatunnel-ui/src/layouts/dashboard/header/user/index.tsx
> [Feat][UI] Add menu selection and username drop-down.

- seatunnel-ui/src/layouts/dashboard/header/user/use-user-dropdown.ts
- seatunnel-ui/src/views/data-pipes/create/index.tsx
- seatunnel-ui/src/views/data-pipes/detail/index.tsx
- seatunnel-ui/src/views/data-pipes/list/index.tsx
- seatunnel-ui/src/views/data-pipes/list/use-table.ts
- seatunnel-ui/src/views/jobs/list/index.tsx
- seatunnel-ui/src/views/tasks/list/index.tsx
- seatunnel-ui/src/views/user-manage/list/index.tsx
> [Perf][UI] Optimize some details and styles.

- seatunnel-ui/src/views/login/index.tsx
> Perf login

- seatunnel-ui/src/layouts/dashboard/header/user/index.tsx
- seatunnel-ui/src/layouts/dashboard/header/user/use-user-dropdown.ts
- seatunnel-ui/src/locales/en_US/index.ts
- seatunnel-ui/src/locales/en_US/setting.ts
- seatunnel-ui/src/router/routes.ts
- seatunnel-ui/src/views/setting/index.tsx
- seatunnel-ui/src/views/setting/use-setting.ts
- seatunnel-ui/src/views/tasks/list/index.tsx
> [Feat][UI] Finish writing the setting page.

- seatunnel-ui/src/common/table.ts
- seatunnel-ui/src/locales/en_US/data-pipes.ts
- seatunnel-ui/src/locales/en_US/tasks.ts
- seatunnel-ui/src/locales/en_US/user-manage.ts
- seatunnel-ui/src/store/setting/index.ts
- seatunnel-ui/src/store/setting/types.ts
- seatunnel-ui/src/views/data-pipes/list/use-table.ts
- seatunnel-ui/src/views/jobs/list/use-table.ts
- seatunnel-ui/src/views/setting/index.tsx
- seatunnel-ui/src/views/tasks/list/use-table.ts
- seatunnel-ui/src/views/user-manage/list/use-table.ts
> [Feat][UI] Complete the function of setting table fields.

- seatunnel-ui/src/service/task/index.ts
- seatunnel-ui/src/service/task/types.ts
- seatunnel-ui/src/views/data-pipes/create/index.tsx
- seatunnel-ui/src/views/data-pipes/detail/index.tsx
- seatunnel-ui/src/views/data-pipes/edit/index.tsx
- seatunnel-ui/src/views/data-pipes/list/components/publish-modal.tsx
- seatunnel-ui/src/views/data-pipes/list/index.tsx
- seatunnel-ui/src/views/data-pipes/list/use-table.ts
- seatunnel-ui/src/views/jobs/list/use-table.ts
- seatunnel-ui/src/views/tasks/list/use-table.ts
> [Feat][UI] Add to execute and rerun interfaces.

- seatunnel-ui/src/App.tsx
- seatunnel-ui/src/views/setting/index.tsx
> [Fix][UI] Fix the error of fillet switching.

- .gitmodules
- .licenserc.yaml
> [Chore] Remove useless dependency

- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_mysql.sql
Add `admin` user for using mysql database.
> [Hotfix] Fix admin user for using mysql

- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-mysql/src/main/java/org/apache/seatunnel/datasource/plugin/mysql/jdbc/MysqlJdbcDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-oracle/src/main/java/org/apache/seatunnel/datasource/plugin/oracle/jdbc/OracleDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-postgresql/src/main/java/org/apache/seatunnel/datasource/plugin/postgresql/jdbc/PostgresqlDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-mysql-cdc/src/main/java/org/apache/seatunnel/datasource/plugin/cdc/mysql/MysqlCDCDataSourceChannel.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/SeatunnelDatasourceController.java
> [feature] channel update get tables and add filter by name and size

- seatunnel-ui/src/locales/en_US/datasource.ts
- seatunnel-ui/src/locales/zh_CN/datasource.ts
- seatunnel-ui/src/router/index.ts
- seatunnel-ui/src/views/datasource/list/index.tsx
- seatunnel-ui/src/views/datasource/list/use-columns.ts
- seatunnel-ui/src/views/virtual-tables/list/use-columns.ts
> [feature] add button update and delete

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/SchemaDerivationController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/ISchemaDerivationService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/SchemaDerivationServiceImpl.java
> [feature] add transform sql interface

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/ITableSchemaService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/DatasourceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TableSchemaServiceImpl.java
https://github.com/apache/seatunnel/issues/5259
> [Hotfix] Fix convert virtual table of kafka to table field error

- README.md
> [feature] add st web basedir path

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IJobInstanceHistoryDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobInstanceHistoryDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobMetricsServiceImpl.java
> [bugfix] Job instance history repeat

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/bean/engine/EngineDataType.java
> [bugfix] engine data type get type for lower

- seatunnel-server/seatunnel-app/src/main/resources/connector-datasource-mapper.yaml
> [bugfix] remove tidb because 2.3.3-tidb-no data type convertor

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/SeatunnelDatasourceController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/DatasourceServiceImpl.java
- seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
Fixed an occasional bug where datasource could not be deleted.
> [FixBug][seatunnel-web]Fix delete datasource

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobDefinitionController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IJobTaskDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobTaskDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobTaskService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobTaskServiceImpl.java
Fixed an issue where the jobdefinition was deleted but the job task was not deleted
> [FixBug][seatunnel-web]Fix delete job task

- seatunnel-datasource/seatunnel-datasource-client/src/main/java/org/apache/seatunnel/datasource/AbstractDataSourceClient.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobVersionDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobMetricsServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobTaskServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TableSchemaServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineProxy.java
> [bugfix] seatunnel task is not exist ,job status error bug

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobMetricsServiceImpl.java
[Improve] Fix the typo of "Metrics", and fix the npe when jobStatus is null.
> [Improve] Fix the typo of "Metrics", and fix the npe when jobStatus is null.

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobExecutorController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/TaskInstanceController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobExecutorService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/ITaskInstanceService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskInstanceServiceImpl.java
Optimize the code, add a specific Result type.
> [Improve] Optimize the code, add a specific Result type.

- seatunnel-server/seatunnel-app/pom.xml
- seatunnel-server/seatunnel-dynamicform/pom.xml
- seatunnel-ui/package.json
- seatunnel-ui/vite.config.ts
> [Improve] Remove useless dependencies.

- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_mysql.sql
Null pointer exception is not thrown when creating a new user on seatunnel ui
> [Hotfix] [Seatunnel-Web][seatunnel-server] Null Pointer Exception when try to create new user #5549

- pom.xml
- seatunnel-server/seatunnel-app/pom.xml
1. Delete duplicate dependencies
2. Fix maven-release-plugin error by update maven-release-plugin version to 2.5.3
3. Update scm url
> [Hotfix] fix release error

- pom.xml
> Fix pom style

- seatunnel-server/seatunnel-app/src/main/bin/download_datasource.sh
Add "download_datasource.sh" for downloading datasource.
> [Improve] Add "download_datasource.sh" for downloading datasource.

- build.sh
Build images using flexible version parameters.
> [Improve] Build images using flexible version parameters.

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/VirtualTableServiceImpl.java
> [bugfix] virtual update datasource

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
Modify configuration file generation path rules to adapt to windows and linux
> [Hotfix][APP] Fix job config file generation path error in windows

- seatunnel-ui/src/router/sync-task.ts
- seatunnel-ui/src/router/virtual-tables.ts
- seatunnel-ui/src/service/sync-task-definition/index.ts
[Improve][UI] Translate Route Names
> [Improve][UI] Translate Route Names

- seatunnel-datasource/seatunnel-datasource-client/src/main/java/org/apache/seatunnel/datasource/classloader/DatasourceLoadConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-mongodb/pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-mongodb/src/main/java/com/apache/seatunnel/datasource/plugin/mongodb/MongoDataSoueceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-mongodb/src/main/java/com/apache/seatunnel/datasource/plugin/mongodb/MongoDataSourceFactory.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-mongodb/src/main/java/com/apache/seatunnel/datasource/plugin/mongodb/MongoOptionRule.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-mongodb/src/main/java/com/apache/seatunnel/datasource/plugin/mongodb/MongoRequestParamsUtils.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-plugins-api/src/main/java/org/apache/seatunnel/datasource/plugin/api/DataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/pom.xml
- seatunnel-server/seatunnel-app/src/main/bin/download_datasource.sh
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/MongoDBDataSourceConfigSwitcher.java
- seatunnel-server/seatunnel-app/src/main/resources/connector-datasource-mapper.yaml
- seatunnel-web-dist/pom.xml
> [feature] add mongodb datasource

- seatunnel-server/seatunnel-app/src/main/resources/application.yml
> fix: update "driver-class-name: com.mysql.cj.jdbc.Driver" for mysql8

- seatunnel-datasource/seatunnel-datasource-client/src/main/java/org/apache/seatunnel/datasource/classloader/DatasourceLoadConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-all/pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2DataSourceConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2JdbcDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2JdbcDataSourceFactory.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2OptionRule.java
- seatunnel-datasource/seatunnel-datasource-plugins/pom.xml
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/Db2DataSourceConfigSwitcher.java
- seatunnel-server/seatunnel-app/src/main/resources/connector-datasource-mapper.yaml
- seatunnel-web-dist/pom.xml
> [feature][datasource] Main add datasource-jdbc-db2

- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2JdbcDataSourceChannel.java
- seatunnel-server/seatunnel-app/src/main/resources/application.yml
> [Fix] Remove secretKey in application.yml

- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-mysql/src/main/java/org/apache/seatunnel/datasource/plugin/mysql/jdbc/MysqlJdbcDataSourceChannel.java
- tools/dependencies/known-dependencies.txt
link
https://github.com/apache/security-site/commit/5a193b7e29dc616d019784ca9fbf1671f3f0b4d2
> [Hotfix] Fix arbitrary file readvulnerability on mysql jdbc

- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-starrocks/src/main/java/org/apache/seatunnel/datasource/plugin/starrocks/jdbc/StarRocksJdbcDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-tidb/src/main/java/org/apache/seatunnel/datasource/plugin/tidb/jdbc/TidbJdbcDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-starrocks/src/main/java/org/apache/seatunnel/datasource/plugin/starrocks/StarRocksCatalog.java
link https://github.com/apache/security-site/commit/5a193b7e29dc616d019784ca9fbf1671f3f0b4d2
> [Hotfix] Fix arbitrary file readvulnerability on mysql jdbc(starrocks/tidb)

- README.md
- README_CN.md
> Update doc of jwt.secretKey

- README.md
> Update README.md for fix the seatunnel.sh cmd

- README.md
Reverts apache/seatunnel-web#158
> Revert "Update README.md for fix the seatunnel.sh cmd"

- seatunnel-datasource/seatunnel-datasource-client/src/main/java/org/apache/seatunnel/datasource/classloader/DatasourceLoadConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-console/pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-console/src/main/java/org/apache/seatunnel/datasource/plugin/console/ConsoleDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-console/src/main/java/org/apache/seatunnel/datasource/plugin/console/ConsoleDataSourceConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-console/src/main/java/org/apache/seatunnel/datasource/plugin/console/ConsoleDataSourceFactory.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-fakesource/pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-fakesource/src/main/java/org/apache/seatunnel/datasource/plugin/fakesource/FakeSourceDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-fakesource/src/main/java/org/apache/seatunnel/datasource/plugin/fakesource/FakeSourceDataSourceConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-fakesource/src/main/java/org/apache/seatunnel/datasource/plugin/fakesource/FakeSourceDataSourceFactory.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-plugins-api/src/main/java/org/apache/seatunnel/datasource/plugin/api/DatasourcePluginTypeEnum.java
- seatunnel-server/seatunnel-app/src/main/bin/download_datasource.sh
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/ConnectorServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/ConsoleDataSourceConfigSwitcher.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/FakeSourceDataSourceConfigSwitcher.java
- seatunnel-server/seatunnel-app/src/main/resources/connector-datasource-mapper.yaml
- seatunnel-server/seatunnel-app/src/main/resources/i18n_en.config
- seatunnel-server/seatunnel-app/src/main/resources/i18n_zh.config
- seatunnel-ui/src/hooks/use-source-type.ts
- seatunnel-ui/src/locales/en_US/datasource.ts
- seatunnel-ui/src/locales/en_US/project.ts
- seatunnel-ui/src/locales/zh_CN/datasource.ts
- seatunnel-ui/src/locales/zh_CN/project.ts
- seatunnel-ui/src/views/datasource/components/use-source.ts
- seatunnel-ui/src/views/datasource/list/use-source.ts
- seatunnel-web-dist/pom.xml
Added FakeSource and Console data sources for quick testing and to use these datasource in test automation.
> [Feature][Seatunnel-web] Add FakeSource and Console data sources into seatunnel-web

- pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-tidb/pom.xml
> [Build] Update snapshot version to 1.0.2

- seatunnel-server/seatunnel-app/src/main/bin/seatunnel-backend-daemon.sh
Creating logs directory if it does not exist.
> [Bug] [Seatunnel-web] Create log directory if it does not exist.

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineMetricsExtractor.java
> [Chore] Code clean

- pom.xml
- tools/dependencies/known-dependencies.txt
Upgraded plugins which were using velocity-1.7, also upgraded some other plugins for CVE remediation
> [Improvement] [Seatunnel-web] velocity-1.7.jar have multiple CVEs, upgrade all maven plugins which depend on this.

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobDefinitionServiceImpl.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobDefinitionControllerTest.java
Corrected logic to create stream job
Also changed engine version from 2.3.0 to 2.3.7
> [Bug] [Seatunnel-web] Job mode is hardcoded, job create API is always creates BATCH job

- README.md
> [Improve] Update README.md for version 2.3.8

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/TaskInstanceController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IJobInstanceDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobInstanceDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/entity/JobInstance.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/entity/JobVersion.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/engine/Engine.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/executor/JobExecutorRes.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobMetricsService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/ITaskInstanceService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/EngineServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobConfigServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobDefinitionServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobMetricsServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskInstanceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/metrics/EngineMetricsExtractorFactory.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobConfigControllerWrapper.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobDefinitionControllerWrapper.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/TaskInstanceControllerWrapper.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/domain/JobExecutorResDeserializer.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobControllerTest.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobDefinitionControllerTest.java
Change JobMode and EngineType to enum type to avoid hard coding
> [Improve][SeaTunnel-Web] Change JobMode and EngineType to enum type to avoid hard coding

- seatunnel-datasource/seatunnel-datasource-client/src/main/java/org/apache/seatunnel/datasource/classloader/DatasourceLoadConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-hive/pom.xml
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/jdbc/HiveJdbcConstants.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/jdbc/HiveJdbcDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/jdbc/HiveJdbcDataSourceFactory.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/jdbc/HiveJdbcOptionRule.java
- seatunnel-datasource/seatunnel-datasource-plugins/pom.xml
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/bean/engine/EngineDataType.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/HiveJdbcDataSourceConfigSwitcher.java
- seatunnel-server/seatunnel-app/src/main/resources/connector-datasource-mapper.yaml
> [Improvement][Seatunnel-web][Hive-JDBC] Add Hive-JDBC into seatunnel-web

- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2DataSourceConfig.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2JdbcDataSourceChannel.java
- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-db2/src/main/java/org/apache/seatunnel/datasource/plugin/db2/jdbc/Db2OptionRule.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/bean/engine/EngineDataType.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/Db2DataSourceConfigSwitcher.java
Corrected all db2 related issues mentioned in the corresponding issue
> [Bug][Seatunnel-web][DB2] DB2 Datasource fails due to improper use of database and schema names.

- README.md
- README_CN.md
> [Doc]init deploy readme optimize

- README.md
- README_CN.md
Documented configuration placeholder feature
> [Improvement][Seatunnel-web] Document Placeholder feature

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/config/MybatisPlusConfig.java
> [Bug] [Seatunnel-web] Tasks pagination is not working

- README.md
> [Improve][Doc] Add compatibility in doc

- seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-oracle/src/main/java/org/apache/seatunnel/datasource/plugin/oracle/jdbc/OracleDataSourceChannel.java
While configuring Oracle Jdbc Source, users are unable to fetch table fields, as table name is passed as an argument in the format `schema`.`table`. 
Fixes Issue: https://github.com/apache/seatunnel/issues/7985
> [Bug][Seatunnel-web] Fix fetch table fields for Oracle Jdbc

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/BaseJdbcDataSourceConfigSwitcher.java
> [Bug] [Seatunnel-web] No configuration setting found for key 'where_c…ondition'

- seatunnel-ui/src/views/task/synchronization-definition/dag/sidebar/index.tsx
> [Bug] [Seatunnel-web] fix build prod

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobServiceImpl.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobControllerTest.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/utils/JobTestingUtils.java
> [Bug][Seatunnel-web] Job update API fails when tasks are added or removed

- seatunnel-ui/src/assets/styles/default.scss
- seatunnel-ui/src/locales/en_US/index.ts
- seatunnel-ui/src/locales/zh_CN/index.ts
- seatunnel-ui/src/views/task/synchronization-definition/dag/index.tsx
Support Chinese and English display.
> [Imporve]Support Chinese and English display.

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobDefinitionController.java
- seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
> [Improve] Improve create task name duplicate

- seatunnel-ui/src/locales/en_US/project.ts
- seatunnel-ui/src/locales/zh_CN/project.ts
- seatunnel-ui/src/views/task/synchronization-definition/dag/configuration-form.tsx
- seatunnel-ui/src/views/task/synchronization-definition/dag/types.ts
- seatunnel-ui/src/views/task/synchronization-definition/dag/use-configuration-form.ts
> [Improve]Support Sink input table name

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineMetricsExtractor.java
> [Improve] Delete duplicate code

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobInstanceDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/dto/job/SeaTunnelJobInstanceDto.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskInstanceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.xml
- seatunnel-ui/src/views/task/synchronization-instance/use-sync-task.ts
- Display user nickname
- Optimize SQL query
Before
After
> [Improve] Display user nickname

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobTaskServiceImpl.java
Support multi-table sink
Before:
After:
> [feature] Support multi-table sink

- seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.xml
After https://github.com/apache/seatunnel-web/pull/266 merge TaskInstanceControllerTest started failing.
Made changes to make script compatible to H2 database
> TaskInstanceControllerTest started failing

- README.md
- README_CN.md
- pom.xml
- seatunnel-server/seatunnel-app/pom.xml
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/common/Constants.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/config/ConfiguredAuthenticationProvider.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/config/LdapAuthenticationBuilder.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/config/SeatunnelAuthenticationProvidersConfig.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/config/SeatunnelLdapAuthenticationProvider.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/UserController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IUserDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/UserDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/entity/User.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/mapper/UserMapper.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/dto/user/UpdateUserDto.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/security/authentication/strategy/IAuthenticationStrategy.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/security/authentication/strategy/impl/DBAuthenticationStrategy.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/security/authentication/strategy/impl/LDAPAuthenticationStrategy.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IUserService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/UserServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/resources/application.yml
- seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/UserMapper.xml
- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_h2.sql
- seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_mysql.sql
- seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/common/SeatunnelWebTestingBase.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/UserControllerTest.java
- seatunnel-web-it/src/test/resources/application.yml
- tools/dependencies/known-dependencies.txt
We need to add support for LDAP authentication. It is important to centralise user identification with already existing authentication services within Organisation, so that users can use the LDAP credentials across applications. 
> [LDAP][Seatunnel-web] Add LDAP Authentication Provider Support.

- README_CN.md
fix readme_cn.md word spell error
> [Doc] Fix README_CN.md Word Spell Error

- .dlc.json
> [Fix] Fix dead link

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/ResourceNameProviderController.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IDatasourceDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IJobDefinitionDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IUserDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IVirtualTableDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IWorkspaceDao.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/DatasourceDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobDefinitionDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/UserDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/VirtualTableDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/WorkspaceDaoImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/mapper/WorkspaceMapper.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IDatasourceService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobDefinitionService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IUserService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IVirtualTableService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/WorkspaceService.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/DatasourceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobDefinitionServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/UserServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/VirtualTableServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/WorkspaceServiceImpl.java
- seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/UserMapper.xml
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/ResourceNameProviderControllerWrapper.java
- seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/ResourceNameProviderControllerTest.java
The resource name provider APIs will be used by Ranger seatunnel plugin to autocomplete resource names.
> [Feature] Add APIs to get resource names.

- seatunnel-ui/src/locales/en_US/login.ts
- seatunnel-ui/src/locales/en_US/user-manage.ts
- seatunnel-ui/src/locales/zh_CN/login.ts
- seatunnel-ui/src/locales/zh_CN/user-manage.ts
- seatunnel-ui/src/service/user/index.ts
- seatunnel-ui/src/service/user/types.ts
- seatunnel-ui/src/store/setting/index.ts
- seatunnel-ui/src/store/setting/types.ts
- seatunnel-ui/src/views/login/index.tsx
- seatunnel-ui/src/views/login/use-form.ts
(This enables users to selects workspace from ui, this is corresponding Front End PR for following workspace integration feature.)
- [Add APIs to get resource names](https://github.com/apache/seatunnel-web/pull/286)
- [Add Support for Authorization ](https://github.com/apache/seatunnel-web/pull/285)
- [Add Workspace Support](https://github.com/apache/seatunnel-web/pull/284)
- [Add LDAP Authentication Provider Support](https://github.com/apache/seatunnel-web/pull/269)
> [Improve] Enable Selecting Workspace and LDAP from UI

- build.cmd
> [Improve] Support windows build script

- seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/scheduler/MonitorTaskScheduler.java
> [Feature] Add creation and update timestamps to monitor task metrics
