seatunnel-ui/src/views/virtual-tables/detail.tsx

When building, it shows a file not found error.

fix: file not found

---

seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_mysql.sql

Update seatunnel_server_mysql.sql 
fix   
sh seatunnel-server/seatunnel-app/src/main/resources/script/init_sql.sh
ERROR 1046 (3D000) at line 24: No database selected

Update seatunnel_server_mysql.sql fix   ERROR 1046 (3D000) at line 24: No database selected

---

seatunnel-datasource/seatunnel-datasource-plugins/datasource-mysql-cdc/src/main/java/org/apache/seatunnel/datasource/plugin/cdc/mysql/MysqlCDCDataSourceChannel.java

[Hotfix] Fix arbitrary file readvulnerability on mysql cdc

---

pom.xml
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/bean/engine/EngineDataType.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/EngineServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/SchemaDerivationServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TableSchemaServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineProxy.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/framework/PluginDiscoveryUtil.java
seatunnel-ui/src/layouts/dashboard/index.tsx
tools/dependencies/known-dependencies.txt

Add support for Seatunnel 2.3.5 in Seatunnel-Web.
Build seatunnel-web with the proposed the code changes, installed  and verified that jobs are successfully executed on seatunnel 2.3.5 engines. Verification snapshot attached

[Improve] [Seatunnel-Web] Add support for Seatunnel 2.3.6 in Seatunnel-Web

---

seatunnel-server/seatunnel-app/src/main/bin/seatunnel-backend-daemon.sh

After fix below seatunnel-web start command creates logs,out file and gc files inside logs directory
sh bin/seatunnel-backend-daemon.sh start

[Bug] [Seatunnel-web] gc.log, nohup.out is created outside of logs directory

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java

Problem:
Seatunnel-web always requires the cluster name to be "seatunnel"
I configured "cluster-name: seatunnel-test" in hazelcast.yaml and also added "cluster-name: seatunnel-test" in hazelcast-client.yaml in seatunnel-web config, job execution was failing.
Proposal:
Remove the hard coding of cluster name. Read the cluster name from hazelcast-client.yam

[Bug] [Seatunnel-web] Seatunnel-web always requires the cluster name to be seatunnel

---

seatunnel-ui/src/assets/styles/default.scss
seatunnel-ui/src/views/task/synchronization-definition/dag/sidebar/index.module.scss
seatunnel-ui/src/views/task/synchronization-definition/dag/sidebar/index.tsx

When screen height is reduced or more items added in the task synchronization definition sidebar, tiles are falls out of the task synchronization definition sidebar.
This PR aims to enhance user experience by improving navigation through the task synchronization process and Fixed the above mentioned bug.
**Changes Introduced:**
Tooltips for Task Tiles : Added tooltips to the Source, Sink, and Transform tiles in the task synchronization definition sidebar. The tooltips provide guidance on dragging and configuring the tiles.
Bug Fix : Addressed a bug that affected the display of the sidebar when the screen height was reduced or when more items were added.
**How It Works:**
Hover Over Info Icon : When hovering over the Info icon added to the right side of the task synchronization definition …

[Improve][feature][Bug] Add Tooltip and  Fix Design Issue In the Task Definition

---

pom.xml
seatunnel-web-dist/pom.xml
tools/dependencies/known-dependencies.txt

Changed frontend-maven-plugin from 1.11.3 to 1.15.0 to download correct node package
Changed slf4j.version from 1.7.25 to 1.7.36 to remediate CVS

[Improvement][Seatunnel-web] Bump frontend-maven-plugin from 1.11.3 to 1.15.0 and slf4j.version from 1.7.25 to 1.7.36

---

seatunnel-web-dist/src/main/assembly/seatunnel-web-ci.xml
seatunnel-web-dist/src/main/assembly/seatunnel-web.xml

Changed the default permission to 755

[Bug] [Seatunnel-web] seatunnel-web start and plugin download scripts by default do not have execute permission

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobExecutorController.java
seatunnel-ui/src/service/sync-task-definition/index.ts
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobExecutorControllerWrapper.java

Changed /seatunnel/api/v1/job/executor/execute method from GET to POST

[Improvement][Seatunnel-web] Execute job REST API should be of type POST, not GET

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/common/Result.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobController.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/request/connector/JobMode.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/request/job/JobCreateReq.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobService.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobTaskServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/GlobalExceptionHandler.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/ParamValidationException.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobControllerTest.java
seatunnel-web-it/src/test/resources/jobs/fake_source_console_job.json

This PR adds support to create job in single call. You can create job with one API instead of calling following four API
POST seatunnel/api/v1/job/definition
POST seatunnel/api/v1/job/task/{jobVersionId}
PUT seatunnel/api/v1/job/config/{jobVersionId}
POST seatunnel/api/v1/job/dag/{jobVersionId}
In jobDAG for inputPluginId and targetPluginId use the plugin configuration names instead of ids to make the API feasible.

[Feature][Seatunnel-web] Add support to create job with single API

---

seatunnel-ui/src/locales/en_US/common.ts
seatunnel-ui/src/locales/zh_CN/common.ts
seatunnel-ui/src/utils/time.ts
seatunnel-ui/src/views/virtual-tables/detail.tsx
seatunnel-ui/src/views/virtual-tables/use-detail.ts

[Fix]Fix the run_time calculation to account for missing days.

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/common/Result.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/GlobalExceptionHandler.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/SeatunnelDatasourceControllerTest.java

Corrected the logic to return validation messages.

[Bug] [Seatunnel-web] Validation messages are wrong

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobExecutorController.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/request/job/JobExecParam.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobInstanceService.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobTaskServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/JobExecParamUtil.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobExecutorControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/SeatunnelDatasourceControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/utils/JobUtils.java
seatunnel-web-it/src/test/resources/jobs/mysql_source_mysql_sink.json

Added support to execute job with paramters.
Here is the sample job execution parameters.Every aspect the job can be changed at execution.
{
"env": {
"ENV_VAR1": "value1",
"ENV_VAR2": "value2"
},
"tasks": {
"task1_name": {
"param1": "value1",
"param2": "value2"
},
"task2_name": {
"param1": "value3",
"param2": "value4"
}
},
"datasource": {
"task1_name": "123_datasource_id",
"task2_name": "456_datasource_id"
}
}

[Feature] [Seatunnel-web] Add support to execute job with parameter through API.

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java

Changed the job staus to failed when job submission failed.

[Bug] [Seatunnel-web] When job execution initialization fails, the job execution status remains unchanged.

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobExecutorController.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobExecutorControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/domain/JobExecutorResDeserializer.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/utils/JSONTestUtils.java

[Bug] [Seatunnel-web] GET /seatunnel/api/v1/job/executor/resource API is not using logged-in user.

---

README.md
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/entity/JobInstance.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobInstanceService.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/JobExecParamUtil.java
seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.xml
seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_h2.sql
seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_mysql.sql
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobTaskControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/TaskInstanceControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/TaskInstanceControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/utils/JobUtils.java
seatunnel-web-it/src/test/resources/hazelcast.yaml

Added job failure log into the t_st_job_instance table.

[Improvement] [Seatunnel-web] Add support to provide reason for job failure

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobExecutorController.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IJobInstanceDao.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobInstanceDaoImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/executor/JobExecutionStatus.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/ITaskInstanceService.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.xml
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobExecutorControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java

Currently, there is no direct API to get job execution status.
Add following two APIs
/seatunnel/api/v1/job/executor/status --> this should return jobStatus and errorMessage
/seatunnel/api/v1/job/executor/detail --> this should return SeaTunnelJobInstanceDto which includes jobStatus, errorMessage and other details
Both APIs accept jobVersionId as the parameter

[Improvement] [Seatunnel-web] Add API to get job execution status.

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobController.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/job/JobRes.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IJobService.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobConfigServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskInstanceServiceImpl.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobControllerTest.java

As part of https://github.com/apache/seatunnel-web/commit/f45dacd11759bcf0fb0ad363b334d0a00af5e69a we have added single API to create a job. There should be corresponding get and update APIs also. So added following two APIs
GET /seatunnel/api/v1/job/get/{jobVersionId}
PUT /seatunnel/api/v1/job/update/{jobVersionId}

[Improvement] [Seatunnel-web] Add API to get and update job definition.

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/DatasourceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineMetricsExtractor.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/JobUtils.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobMetricsControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/TaskInstanceControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/utils/JobTestingUtils.java

Renamed JobExecParamUtil and JobUtils.
Removed exta db call in DatasourceServiceImpl 
Removed suplicate codes from SeaTunnelEngineMetricsExtractor, and DatasourceServiceImpl
Removed redunant code to set cluster name

[Improvement] [Seatunnel-web] Improve code in DatasourceServiceImpl,SeaTunnelEngineMetricsExtractor etc.

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/JobExecutorController.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IJobInstanceDao.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobInstanceDaoImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/ITaskInstanceService.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskInstanceServiceImpl.java
seatunnel-ui/src/service/sync-task-instance/index.ts
seatunnel-ui/src/views/task/synchronization-instance/use-sync-task.ts
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobExecutorControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java

Added DELETE /seatunnel/api/v1/job/executor/delete API and called this API from UI code 

[Bug] [Seatunnel-web] Job instance delete is not working

---

pom.xml
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/controller/TaskInstanceController.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/IJobInstanceDao.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/dao/impl/JobInstanceDaoImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/TaskInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/JobInstanceMapper.xml
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/TaskInstanceControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/TaskInstanceControllerTest.java
tools/dependencies/known-dependencies.txt

Corredcted task instance filter logic
Changed logback version to 1.2.3

[Bug][Seatunnel-web] Task instance filter is not working as expected

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobMetricsServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineMetricsExtractor.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/metrics/IEngineMetricsExtractor.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/JobUtils.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java

1.Changed logic to use job status from databse instead of seatunnel-engine.
2.If job is ended then not fetching metrics from seatunnel-engine but fetching from database.
3 Handeled error while fetching metrics from seatunnel-engine.

[Bug] [Seatunnel-web] [Metrics] NPE while fetching metrics from seatunnel-engine.

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/entity/JobInstance.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/dal/entity/JobMetrics.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/executor/JobExecutionStatus.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/metrics/JobPipelineDetailMetricsRes.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/metrics/JobPipelineSummaryMetricsRes.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/metrics/JobSummaryMetricsRes.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/response/task/JobSimpleInfoRes.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobMetricsServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineMetricsExtractor.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/engine/SeaTunnelEngineProxy.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/metrics/IEngineMetricsExtractor.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/JobUtils.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/TaskInstanceControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/utils/JobTestingUtils.java

Change JobStatus to enum type to avoid hard coding

[Improve][SeaTunnel-Web] Change JobStatus to enum type to avoid hard coding

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/domain/request/job/JobExecParam.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobExecutorServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/JobUtils.java
seatunnel-server/seatunnel-app/src/test/java/org/apache/seatunnel/app/utils/JobUtilsTests.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/controller/JobControllerWrapper.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/JobExecutorControllerTest.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/utils/JobTestingUtils.java
seatunnel-web-it/src/test/resources/jobs/fake_source_console_job.json
seatunnel-web-it/src/test/resources/logback-spring.xml

[Feature][Seatunnel-web]Add support to configure placeholder with default value in the job config.

---

seatunnel-server/seatunnel-app/src/main/resources/connector-datasource-mapper.yaml
seatunnel-server/seatunnel-app/src/test/java/org/apache/seatunnel/app/utils/JobUtilsTests.java

1. Added Hive entry in connector-datasource-mapper.yaml
2. Corrected a small mistake in previous commit in a test class

[Bug] [Seatunnel-web][Hive] Hive data source is not appearing in UI during the configuration of the Hive source.

---

seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/com/whaleops/datasource/datasource/plugin/hive/HiveOptionRule.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/com/whaleops/datasource/datasource/plugin/hive/client/HiveClient.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/HiveDataSourceConfigSwitcher.java

Added HiveDataSourceConfigSwitcher and corrected logic to populate correct fields for Hive Source

[Bug][Seatunnel-web][Hive] An error occurred during the attempt to save a job using the Hive connector.

---

seatunnel-datasource/seatunnel-datasource-client/src/main/java/org/apache/seatunnel/datasource/classloader/DatasourceLoadConfig.java
seatunnel-datasource/seatunnel-datasource-client/src/test/java/org/apache/seatunnel/datasource/S3DatasourceChannelTest.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveConfig.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveConstants.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveDataSourceChannel.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveDataSourceFactory.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveOptionRule.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/client/HiveClient.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/IDatasourceService.java

Renamed package com.whaleops.datasource to org.apache.seatunnel

[Improvement][Seatunnel-web] Rename package com.whaleops.datasource to org.apache.seatunnel

---

seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/UserMapper.xml
seatunnel-server/seatunnel-app/src/main/resources/script/seatunnel_server_h2.sql
seatunnel-web-it/README.md
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/common/SeaTunnelWebCluster.java
seatunnel-web-it/src/test/resources/application.yml

[Improvement][Seatunnel-web] Support H2 database in integration tests

---

seatunnel-server/seatunnel-app/src/main/resources/connector-datasource-mapper.yaml

Removed HDBC-Hive from sink datasource list

[Bug] [Seatunnel-web] HiveJDBC should not be used as a sink datasource

---

seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveConfig.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveConstants.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveDataSourceChannel.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/HiveOptionRule.java
seatunnel-datasource/seatunnel-datasource-plugins/datasource-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/client/HiveClient.java

Not listing system databses
Deleted unused codes

[Bug][Seatunnel-web][Hive] Filter system databases

---

seatunnel-datasource/seatunnel-datasource-plugins/datasource-jdbc-hive/src/main/java/org/apache/seatunnel/datasource/plugin/hive/jdbc/HiveJdbcDataSourceChannel.java

Passed the database name correctly

[Bug] [Seatunnel-web] [HiveJDBC] Duplicate columns are displayed in source

---

README_CN.md
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/framework/SeaTunnelOptionRuleWrapper.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/JobUtils.java
seatunnel-server/seatunnel-app/src/test/java/org/apache/seatunnel/app/utils/JobUtilsTests.java
seatunnel-server/seatunnel-dynamicform/src/main/java/org/apache/seatunnel/app/dynamicforms/PlaceholderUtil.java
seatunnel-server/seatunnel-dynamicform/src/test/java/org/apache/seatunnel/app/dynamicforms/PlaceholderUtilTest.java

1. An option to escape placeholders in the configuration has been provided. 
2. If a placeholder is escaped by adding a backslash (e.g., \${valueParam:defaultValue}), it is passed to the Seatunnel engine as-is without value being replaced in Seatunnel-web. 
3. laceholders configured as default values in connectors are escaped before being displayed in the UI.

[Bug][Seatunnel-web] Escape seatunnel-web placeholders

---

seatunnel-web-dist/src/main/assembly/seatunnel-web-ci.xml
seatunnel-web-dist/src/main/assembly/seatunnel-web.xml

Copied mvnw,  mvnw.cmd and .mvn/wrapper/maven-wrapper.properties to seatunnel artifact

[Bug][Seatunnel-web] download_datasource.sh fails due to missing mvnw command

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/framework/SeaTunnelOptionRuleWrapper.java

Enum values were not converted to string properly, corrected it

[Bug][Seatunnel-web][Addendum] Escape seatunnel-web placeholders

---

README_CN.md

Update README_CN.md for version 2.3.8

[Improve][SeaTunnel-Web] Update README_CN.md for version 2.3.8

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/Db2DataSourceConfigSwitcher.java

Currently we enforce sending sink insert query, forcing user to not support upsert scenarios. 
Please refer: 
ISSUE: https://github.com/apache/seatunnel/issues/4434
PR (Upsert DB2 Support): https://github.com/apache/seatunnel/pull/7879

[Improve] use generate_sink_sql=true for db2 upsert

---

README.md
README_CN.md
pom.xml
seatunnel-web-it/README.md

[Build] Update snapshot version to 1.0.3

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/BaseJdbcDataSourceConfigSwitcher.java

[Addendum][Bug] [Seatunnel-web] Error when conditional column is not used in SE

---

seatunnel-server/seatunnel-app/src/main/bin/seatunnel-backend-daemon.sh

Fix: The status of seatunnel-web returned by the script `seatunnel-backend-daemon.sh` is always "not running"

[Bug] [Seatunnel-web] Fix  status always not runnning

---

seatunnel-ui/src/components/dynamic-form/dynamic-form-item.tsx
seatunnel-ui/src/locales/en_US/index.ts
seatunnel-ui/src/locales/en_US/project.ts
seatunnel-ui/src/locales/en_US/transforms.ts
seatunnel-ui/src/locales/zh_CN/index.ts
seatunnel-ui/src/locales/zh_CN/project.ts
seatunnel-ui/src/locales/zh_CN/transforms.ts

Support the display of Transforms description information

[Imporve] Support the display of Transforms description information

---

seatunnel-ui/src/views/task/synchronization-instance/detail/task-definition.module.scss
seatunnel-ui/src/views/task/synchronization-instance/detail/task-definition.tsx

Optimize task description display
Before:
After:

[Improve] Optimize task description display

---

seatunnel-ui/src/views/task/synchronization-instance/use-sync-task.ts

In the "Synchronizing task instances" page, currently the default query is for tasks of the current day. Under normal circumstances, we need to view more data and set the default range to 30 days.

[Improve] Modify the default number of days for query tasks.

---

seatunnel-ui/src/locales/en_US/project.ts
seatunnel-ui/src/locales/zh_CN/project.ts
seatunnel-ui/src/views/task/synchronization-definition/use-table.ts

After running a task currently, there is no operation. We should jump to the task details after creating a task, which is more convenient to use.
Optimization:
1. New feature: Prevent repeated task submission by continuous clicking.
2. After submitting a task, jump to the task details.
https://github.com/user-attachments/assets/c757c7f0-0c3e-4db5-a332-7a824fb9e07a

[feature] After run a task, jump to the task details page

---

seatunnel-server/seatunnel-app/src/main/resources/org/apache/seatunnel/app/dal/mapper/UserMapper.xml
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
seatunnel-web-it/src/test/java/org/apache/seatunnel/app/test/UserControllerTest.java

[Bug] Disabled users are able to login

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobMetricsServiceImpl.java

immediately after task execution start, task instance page is opened. For small jobs it is throwing following errors
2025-01-29 12:06:18.800 seatunnel WM-TVJM7KC4Y4 ERROR [tr:,sp:] [qtp431300939-38] [GlobalExceptionHandler.logError():78] -
; Duplicate entry '16473878314272' for key 't_st_job_instance_history.PRIMARY'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '16473878314272' for key 't_st_job_instance_history.PRIMARY'
org.springframework.dao.DuplicateKeyException:
; Duplicate entry '16473878314272' for key 't_st_job_instance_history.PRIMARY'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '16473878314272' for key 't_st_job_instance_history.PRIMARY'
at …

[Bug] DuplicateKeyException encountered while retrieving the job execution history

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/common/Constants.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/config/EncryptionConfig.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/DatasourceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/JobInstanceServiceImpl.java
seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/utils/ConfigShadeUtil.java
seatunnel-server/seatunnel-app/src/main/resources/application.yml
seatunnel-web-it/src/test/resources/application.yml

While writing intermediate config to submit job via seatunnel client, we are required to encrypt certain fields like password, auth, username
By Default no encryption would be done, to enable the encryption provide the following properties
```
seatunnel-web:
datasource:
encryption:
type: your_encryption
keys-to-encrypt:
- password
- auth
```
ref: https://seatunnel.apache.org/docs/2.3.9/connector-v2/Config-Encryption-Decryption/

[Feature] Add Support for encrypting config fields

---

seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/service/impl/UserServiceImpl.java
seatunnel-server/seatunnel-server-common/src/main/java/org/apache/seatunnel/server/common/SeatunnelErrorEnum.java
seatunnel-ui/src/views/user-manage/list/use-table.ts

[Improve] User cannot delete themselves

---

pom.xml

**Issue:**
After build, generated rpm.xml still contain ${revision}
Not able to build subproject directly, always need to build the project from start to end.
**Solution:**
flatten-maven was declared but not used. Used flatten-maven plugin to solve the problems.

[Bug] Version is not getting replaced in pom.xml
